import { useRouter } from "next/router";
import { useEffect, useMemo } from "react";
import styled from "@emotion/styled";
import Navigation from "@/app/\bcomponents/ui/Navigation";
import "@/app/styles/globals.css";

// function AppLayout({ children }: { children: React.ReactChild }) {
//   const router = useRouter();
//   const isHome = useMemo(() => router.asPath === "/", [router.asPath]);

//   return (
//     <>
//       <Navigation />
//       <LayoutWrapper isHome={isHome}>
//         <>{children}</>
//       </LayoutWrapper>
//     </>
//   );
// }

// export default AppLayout;

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <Navigation />
        <LayoutWrapper isHome={false}>
          <>{children}</>
        </LayoutWrapper>
      </body>
    </html>
  );
}

const LayoutWrapper = styled.div<{ isHome: boolean }>`
  padding-top: ${({ isHome }) => (isHome ? "72px" : "0px")};
`;
